services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000"   # expose internally, not mapped to host
    environment:
      - DB_SERVER=gnanabi.database.windows.net
      - DB_PORT=1433
      - DB_DATABASE=mansion
      - DB_USER=servergnanaabi
      - DB_PASSWORD=serverpassword@123
      - EXPRESS_PORT=5000
      - NODE_ENV=production
    deploy:
      replicas: 3   # Run 3 containers for the API service
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"      # Max 50% of a CPU per container
          memory: 125M     # Max 512 MB RAM per container
        reservations:
          cpus: "0.1"     # Reserve 25% of a CPU
          memory: 64M     # Reserve 256 MB RAM
    networks:
      - mansion-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"     # HTTP port
      - "443:443"   # HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates
    depends_on:
      - frontend
      - backend
    networks:
      - mansion-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://localhost/api
        #- VITE_API_URL=http://68.233.119.219/api
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=https//localhost/api
      #- VITE_API_URL=http://68.233.119.219/api
    deploy:
      resources:
        limits:
          cpus: "0.1"      # Max 50% of a CPU per container
          memory: 125M     # Max 512 MB RAM per container
    networks:
      - mansion-network
    restart: unless-stopped

networks:
  mansion-network:
    driver: bridge
